#!/bin/sh
CLIENT_LINK="http://www.runescape.com/downloads/jagexappletviewer.jar"
GAME_LOC="$HOME/Jagex/Java/OSRS"

if [ ! -d "$GAME_LOC" ]; then
	# Create the directory for the client
	mkdir -p "$GAME_LOC"
	# Download jagexappletviewer.jar
	curl -s -o "$GAME_LOC/jagexappletviewer.jar" "$CLIENT_LINK"
fi
# Run the client
java -Djava.class.path="$GAME_LOC/jagexappletviewer.jar" -Dcom.jagex.config=http://oldschool.runescape.com/jav_config.ws jagexappletviewer "$GAME_LOC" > /dev/null
